- .github/workflows/publish_twopanelayout_ado.yml
- .github/workflows/publish_twopanelayout_mavencentral.yml
- README.md
Moved from [surface-duo-compose-samples repo](https://github.com/microsoft/surface-duo-compose-samples/)
> Add release workflows for TwoPaneLayout

- TwoPaneLayout/README.md
- TwoPaneLayout/dependencies.gradle
Update dependencies and bump release version to alpha09
> Update to Compose version 1.0.5

- README.md
Missed this update in [previous PR](https://github.com/microsoft/surface-duo-compose-sdk/pull/3)
> Update compose version in readme badge

- .github/workflows/publish_twopanelayout_ado.yml
- .github/workflows/publish_twopanelayout_mavencentral.yml
- TwoPaneLayout/build.gradle
- TwoPaneLayout/dependencies.gradle
- TwoPaneLayout/publishing.gradle
To generate and package documentation with our SDK artifacts
> Add dokka to TwoPaneLayout

- ComposeTesting/publishing.gradle
- TwoPaneLayout/library/src/androidTest/java/com/microsoft/device/dualscreen/twopanelayout/LayoutTest.kt
- TwoPaneLayout/library/src/androidTest/java/com/microsoft/device/dualscreen/twopanelayout/TwoPaneTest.kt
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/TwoPaneLayout.kt
- TwoPaneLayout/publishing.gradle
- TwoPaneLayout/sample/build.gradle
- TwoPaneLayout/sample/src/main/java/com/microsoft/device/dualscreen/twopanelayout/MainActivity.kt
- WindowState/publishing.gradle
First draft of navController updates
Note: doesn't include README updates yet, will do this after API has been finalized
I updated the sample to test out the custom navController/navigateToPane1 methods but we don't have to keep it that way:
https://user-images.githubusercontent.com/33138268/157948107-b8329c2c-57c8-40da-806c-29f334c89dd0.mp4
> Add navController parameter to constructor

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
This PR adds issues and PR templates, so we all follow a unified way to explain what a bug, a feature or a PR is about.
> PR and issues templates

- README.md
Updates a twitch stream link to the permanent youtube URL the social links table in the README
Keeps the table updated
Checked the README appearance on the branch
N/A
> Update social links table

- README.md
- TwoPaneLayout/README.md
- TwoPaneLayout/dependencies.gradle
Update version number for TwoPaneLayout to beta04
> Update version number

- ComposeTesting/README.md
- ComposeTesting/dependencies.gradle
- ComposeTesting/library/src/main/java/com/microsoft/device/dualscreen/testing/compose/TestRules.kt
- ComposeTesting/sample/src/androidTest/java/com/microsoft/device/dualscreen/testing/sample/AnnotationTest.kt
- ComposeTesting/sample/src/androidTest/java/com/microsoft/device/dualscreen/testing/sample/FoldingFeatureTest.kt
- ComposeTesting/sample/src/main/java/com/microsoft/device/dualscreen/testing/sample/MainActivity.kt
- README.md
Update ComposeTesting to the new view system library that includes test annotations
To keep both library versions in the test kit in sync
Added new **AnnotationTest.kt** file with tests
New tests
> Update test kit to include test annotations

- .github/workflows/publish_draganddrop_ado.yml
- .github/workflows/publish_draganddrop_mavencentral.yml
Add publish script for DragAndDrop
> Add publish script

- ComposeTesting/README.md
- ComposeTesting/dependencies.gradle
- ComposeTesting/gradle/wrapper/gradle-wrapper.properties
- ComposeTesting/library/build.gradle
- ComposeTesting/library/src/main/AndroidManifest.xml
- ComposeTesting/library/src/main/java/com/microsoft/device/dualscreen/testing/compose/StringHelper.kt
- ComposeTesting/publishing.gradle
- ComposeTesting/sample/build.gradle
- ComposeTesting/sample/src/androidTest/java/com/microsoft/device/dualscreen/testing/sample/AnnotationTest.kt
- ComposeTesting/sample/src/androidTest/java/com/microsoft/device/dualscreen/testing/sample/FoldingFeatureTest.kt
- ComposeTesting/sample/src/androidTest/java/com/microsoft/device/dualscreen/testing/sample/StringTest.kt
- ComposeTesting/sample/src/androidTest/java/com/microsoft/device/dualscreen/testing/sample/SwipeTest.kt
- ComposeTesting/sample/src/main/AndroidManifest.xml
- ComposeTesting/sample/src/main/java/com/microsoft/device/dualscreen/testing/sample/MainActivity.kt
- ComposeTesting/sample/src/main/res/values/strings.xml
- README.md
Updates dependencies for the ComposeTesting library, including bumping to Compose `1.2.0` and gradle `7.2.0`
Also adds new StringHelper methods to use with a `ComposeTestRule`, as the previous methods only worked with an `AndroidComposeTestRule`
Keeps SDKs up to date with the latest stable releases
Ran all sample tests on the Surface Duo, and also tested a private artifact with the tests in the TwoPaneLayout library
Both!
New tests for the new StringHelper method and to add more examples of test annotations
Refactored old tests to fit in with Compose `1.2.0`, now with `AndroidComposeTestRule` there is no need to call `setContent`
> Update ComposeTesting to Compose 1.2.0 and add new StringHelper methods

- DragAndDrop/README.md
- DragAndDrop/dependencies.gradle
- DragAndDrop/library/build.gradle
- DragAndDrop/library/src/main/AndroidManifest.xml
- DragAndDrop/publishing.gradle
- DragAndDrop/sample/build.gradle
- DragAndDrop/sample/src/main/AndroidManifest.xml
- DragAndDrop/sample/src/main/java/com/microsoft/device/dualscreen/draganddrop/ui/view/DropPane.kt
- README.md
Updates dependencies for the DragAndDrop library, including bumping to Compose `1.2.0` and gradle `7.2.0`
Also fixes a small bug in the library sample where the drag text would take priority over the drag image - now, whatever was most recently dragged in will be shown
Keeps SDKs updated on latest stable releases
Tested library sample manually on device, also created a private artifact to test our Compose DragAndDrop sample manually on the device and ran the UI tests for that sample
No
Previous behavior:
Fixed behavior:
> Update DragAndDrop to Compose 1.2.0

- ComposeTesting/library/src/main/java/com/microsoft/device/dualscreen/testing/compose/StringHelper.kt
- README.md
- TwoPaneLayout/README.md
- TwoPaneLayout/dependencies.gradle
- TwoPaneLayout/gradle/wrapper/gradle-wrapper.properties
- TwoPaneLayout/library/build.gradle
- TwoPaneLayout/library/src/androidTest/AndroidManifest.xml
- TwoPaneLayout/library/src/main/AndroidManifest.xml
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/common/PaneSizeUtils.kt
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/twopanelayout/TwoPaneLayoutCore.kt
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/twopanelayoutnav/TwoPaneLayoutNavCore.kt
- TwoPaneLayout/nav_sample/build.gradle
- TwoPaneLayout/nav_sample/src/androidTest/java/com/microsoft/device/dualscreen/twopanelayout/BasicDestinationTest.kt
- TwoPaneLayout/nav_sample/src/androidTest/java/com/microsoft/device/dualscreen/twopanelayout/NavSampleTest.kt
- TwoPaneLayout/nav_sample/src/main/AndroidManifest.xml
- TwoPaneLayout/nav_sample/src/main/java/com/microsoft/device/dualscreen/twopanelayout/BasicDestination.kt
- TwoPaneLayout/sample/build.gradle
- TwoPaneLayout/sample/src/androidTest/java/com/microsoft/device/dualscreen/twopanelayout/SampleTest.kt
- TwoPaneLayout/sample/src/androidTest/java/com/microsoft/device/dualscreen/twopanelayout/TopBarTest.kt
- TwoPaneLayout/sample/src/main/AndroidManifest.xml
- TwoPaneLayout/sample/src/main/java/com/microsoft/device/dualscreen/twopanelayout/MainActivity.kt
Updates library dependencies, including bumping to Compose `1.2.0` and gradle `7.2.0`
Also fixes a pane measurement/size bug that was due to TwoPaneLayout not considering window insets (status bar, navigation bar, etc.) when measuring and laying out content
UPDATE: fixes bug I just found with new ComposeTesting version, string format arguments weren't being passed in correctly
Keeps the SDK updated on the latest stable releases
Ran all of the TwoPaneLayout library tests and sample tests on the Surface Duo
Tried out the pane size bug fix on the 6.7 and 8 emulator, where the bug was previously noticed
Refactored old tests to follow best practices for Compose `1.2.0`
| Version | 6.7 emulator | 8 emulator |
|---|---|---|
| Previous version with bug | ![prev_6 …
> Update TwoPaneLayout to Compose 1.2.0 and fix pane size bug

- ComposeTesting/README.md
- ComposeTesting/dependencies.gradle
- ComposeTesting/gradle/wrapper/gradle-wrapper.properties
- ComposeTesting/library/build.gradle
- ComposeTesting/sample/build.gradle
- DragAndDrop/README.md
- DragAndDrop/dependencies.gradle
- DragAndDrop/gradle/wrapper/gradle-wrapper.properties
- DragAndDrop/library/build.gradle
- DragAndDrop/sample/build.gradle
- README.md
Updates the ComposeTesting and DragAndDrop libraries to Compose `1.3.0`
Keeps the library up to date with the latest stable releases
Ran all UI tests and ran the library samples
Nope
> Update dependencies in ComposeTesting and DragAndDrop libraries

- README.md
- TwoPaneLayout/README.md
- TwoPaneLayout/dependencies.gradle
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/TwoPaneScope.kt
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/twopanelayoutnav/TwoPaneBackStackEntry.kt
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/twopanelayoutnav/TwoPaneLayoutNavCore.kt
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/twopanelayoutnav/TwoPaneNavScopeInstance.kt
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/twopanelayoutnav/TwoPaneNavScopeTest.kt
Updates navigation support by:
- `navigateUpTo(route: String?)` → `navigateBack(): Boolean`
- new `twoPaneBackStack` field
Also updates dependencies to WindowState `1.0.0-alpha07` and Compose `1.3.1`
Based on feedback/testing
Ran existing tests, tested manually on device
N/A
> Update navigation support in TwoPaneLayoutNav

- ComposeTesting/README.md
- ComposeTesting/dependencies.gradle
- DragAndDrop/README.md
- DragAndDrop/dependencies.gradle
- DragAndDrop/library/build.gradle
- README.md
- TwoPaneLayout/README.md
- TwoPaneLayout/dependencies.gradle
- TwoPaneLayout/library/src/androidTest/AndroidManifest.xml
- TwoPaneLayout/library/src/androidTest/java/com/microsoft/device/dualscreen/twopanelayout/NavigateUpToTest.kt
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/TwoPaneScope.kt
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/twopanelayoutnav/TwoPaneNavScopeInstance.kt
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/twopanelayoutnav/TwoPaneNavScopeTest.kt
- WindowState/README.md
- WindowState/dependencies.gradle
Updates dependencies for all libraries, and makes the following changes to TwoPaneLayoutNav:
- removes incorrect support for `launchSingleTop` nav option
- adds `navigateUpTo` method to `TwoPaneNavScope`
Keeps libraries up to date and makes TwoPaneLayoutNav usage more flexible
Ran existing tests and added new tests for `navigateUpTo`
Both
> Update library dependencies and TwoPaneLayout navigation methods

- README.md
- TwoPaneLayout/dependencies.gradle
Updates TwoPaneLayout to new WindowState version `1.0.0-alpha08`
Prepares TwoPaneLayout library for new version release
Ran existing tests
N/A
> Update TwoPaneLayout to new WindowState version

- README.md
Updates release versions in repo readme
This lets new visitors know what the most recent SDK release versions are.
Checked visually
N/A
> Update release versions in readme

- .github/workflows/build_test_check.yml
- WindowState/README.md
- WindowState/dependencies.gradle
- WindowState/gradle.properties
- WindowState/gradle/wrapper/gradle-wrapper.properties
Updates dependencies and gradle version for the WindowState library, notably:
- gradle `8.0.0`
- JWM `1.1.0-beta02`
- compose `1.4.3`
Also bumps version in preparation for release
Keeps library up to date
Ran all UI/unit tests and manually tested sample
N/A
> Update WindowState dependencies

- .github/workflows/publish_composetesting_ado.yml
- .github/workflows/publish_composetesting_mavencentral.yml
- .github/workflows/publish_draganddrop_ado.yml
- .github/workflows/publish_draganddrop_mavencentral.yml
- .github/workflows/publish_twopanelayout_ado.yml
- .github/workflows/publish_twopanelayout_mavencentral.yml
- .github/workflows/publish_windowstate_ado.yml
- .github/workflows/publish_windowstate_mavencentral.yml
Updates all github workflows from JDK 11 to 17
Updating the gradle plugin requires a higher JDK version, as shown by [failed actions](https://github.com/microsoft/surface-duo-compose-sdk/actions/runs/4885902205):
N/A
N/A
> Update all workflows to JDK 17

- ComposeTesting/README.md
- ComposeTesting/dependencies.gradle
- ComposeTesting/gradle.properties
- ComposeTesting/gradle/wrapper/gradle-wrapper.properties
- ComposeTesting/sample/src/androidTest/java/com/microsoft/device/dualscreen/testing/sample/SwipeTest.kt
- DragAndDrop/README.md
- DragAndDrop/dependencies.gradle
- DragAndDrop/gradle.properties
- DragAndDrop/gradle/wrapper/gradle-wrapper.properties
- DragAndDrop/library/src/main/java/com/microsoft/device/dualscreen/draganddrop/DragContainer.kt
- README.md
Updates dependencies for the ComposeTesting and DragAndDrop libraries, including:
- gradle `8.0.0`
- JWM `1.1.0-beta02`
- compose `1.4.3`
Keeps libraries up to date
Ran existing UI tests, tested samples manually on device
Refactored logic in an old test so it would pass on both Surface Duo and any foldable device
> Update dependencies for ComposeTesting and DragAndDrop libraries

- README.md
- TwoPaneLayout/README.md
- TwoPaneLayout/dependencies.gradle
- TwoPaneLayout/gradle.properties
- TwoPaneLayout/gradle/wrapper/gradle-wrapper.properties
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/twopanelayoutnav/TwoPaneBackStackEntry.kt
- TwoPaneLayout/library/src/main/java/com/microsoft/device/dualscreen/twopanelayout/twopanelayoutnav/TwoPaneLayoutNavCore.kt
Updates library dependencies and adds support for navigating with arguments in `TwoPaneLayoutNav`
Addresses community request: https://techcommunity.microsoft.com/t5/surface-duo-sdk/is-twopanebackstackentry-composable-list-of-routes-incompatible/m-p/3790655
Tested manually on device
N/A
> Add argument support for TwoPaneLayoutNav destinations

- README.md
Update release information and social links table in the main repo readme
Keeps repo up to date
N/A
N/A
> Update readme release info and social links
